### ISSUE TITLE
Doesn't work with FontAwesome

### ISSUE THREAD

**Issue by ksinas** [avocadowastaken/babel-plugin-direct-import#27]
I tried this

`.babelrc`
```json
{
  "plugins": [
    ["direct-import",
      {
        "modules": [
          "@fortawesome/free-brands-svg-icons",
        ]
      }
    ]
  ]
}
```
`some.js`
```js
import { faGithub } from '@fortawesome/free-brands-svg-icons'
```
It imports entire svg suit. 

It works with the other plugin though, however this one poorly handles `@material-ui` imports. Would be nice to handle everything with one plugin.

```json
    ["transform-imports", {
      "@fortawesome/free-brands-svg-icons":  {
        "transform": "@fortawesome/free-brands-svg-icons/${member}",
        "preventFullImport": true,
        "skipDefaultConversion": true
      }
    }]
```
this transforms import to 
```js
import { faGithub } from '@fortawesome/free-brands-svg-icons/faGithub'
```

Not that icon is not a default expor.

**Comment by avocadowastaken** [comment]
@ksinas hey! thanks for the report, but unfortunately it's impossible to make it work with the `@fortawesome/free-brands-svg-icons`.

The only thing that plugin does is a static check of the `module` entry of the package, find reexports, and redirects your imports. It works well with `@material-ui/icons` because they reexport all the icons: https://unpkg.com/browse/@material-ui/icons@4.9.1/esm/index.js

But font awesome exports a single file: https://unpkg.com/browse/@fortawesome/free-brands-svg-icons@5.15.1/index.es.js.

So if you're using any modern bundler, you don't need a babel plugin, the bundler will tree shake everything for you.
